### ISSUE TITLE
Feature Request: Delete option for streams

### ISSUE THREAD

**Issue by cptX** [warren-bank/Android-RTSP-IPCam-Viewer#10]
Please add a menu/button for deleting an existing camera/stream

**Comment by warren-bank** [comment]
sorry for the late reply..

when viewing the list of all available cameras/streams..
if you were to swipe a list item (either left or right), then:
* the item will be removed from the list
* the record for the particular camera/stream will be permanently deleted

when viewing the enabled cameras/streams in either a list or a grid..
if you were to swipe a particular camera/stream, then:
* the item will be removed from the list or grid
* the record for the particular camera/stream will be unchanged

there are actually a lot of hidden interactions/gestures that should be fully explained in the README..
I'll write something up and add it.
