### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by matheushcd** [warren-bank/Android-RTSP-IPCam-Viewer#5]
Hello, good afternoon, can this repository be used in my projects? We need something similar here, but without the listing, just showing the video from an IP camera based on RTSP, is it possible then to use this repository, modify it in the case to use in my projects?

**Comment by warren-bank** [comment]
* my app is [GPL-2](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/blob/master/LICENSE.txt)
  - so you can fork it and make changes, but if you publicly release a modified version of the app then you also need to make the changes to its source code public as well
* the version of ExoPlayer library that is used to play the RTSP stream is [Apache-2.0](https://github.com/tresvecesseis/ExoPlayer/blob/865ced05b6a1c817d0f2a5f0381b185c4c29bf82/LICENSE)
  - which (I don't believe) has any copy-left requirement
* as a side-note, [libVLC](https://github.com/warren-bank/Android-libVLC-Demo) plays RTSP streams very well
  - whereas this fork of ExoPlayer is experimental, libVLC has officially supported RTSP for years

**Comment by matheushcd** [comment]
OK understood,

Thanks

Em seg., 30 de nov. de 2020 às 17:00, Warren Bank <notifications@github.com>
escreveu:
