### ISSUE TITLE
How to install, is there any apk?

### ISSUE THREAD

**Issue by cptX** [warren-bank/Android-RTSP-IPCam-Viewer#8]
Hi, how can I install it? Do you have a ready made apk? Is it in Google play store?

**Comment by warren-bank** [comment]
under: [releases](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/releases)

**Comment by cptX** [comment]
In Xiaomi Redmi note 9T 5G is not working properly! I cannot see any stream, it appears black!
